rm(list=ls(all=TRUE))
getwd()
setwd("C:/Users/HP/Documents/R/Curso RGeostats")
require(Rcpp)
library(RGeostats)
#demo(RGeostats.start)
#http://rgeostats.free.fr/forum/viewtopic.php?f=14&t=199&p=445#variography
require(R2I)
require(RShinyAux)
life_classes = read.csv("life_classes.csv",header=T,na="MISS")
life=db.create(life_classes)
#print(life,flag.stats=T)
#Specify the variable roles (locators):
life=db.locate(life,2:3,"x")
life=db.locate(life,4:5,"z")
print(life,flag.stats=T)

polypuma <- read.csv("polyxyfx.csv", header=TRUE, sep=",")
puma<-polygon.create(x = polypuma$x, y=polypuma$y,zmin=NA, zmax=NA, polygon=NA)
polygon.plot(puma)
print(puma)
plot(life)
plot(life,name.post=4,scale=1,pch=21,col=rainbow(10))
par(xaxs="i",yaxs="i")
#SI.stats(life,flag.plot=TRUE)
#SI.cgi(life,flag.plot=TRUE,flag.inertia=TRUE,col=2)
#SI.cgi(db.add(life,S=A0>=0),flag.plot=T,flag.inertia=T,col=1)
gdum = db.create(dx=c(50,50),nx=c(7,11),x0=c(100,500))
hist(life[,5])
db.stat(life,fun="maxi",name=5)
plot(life,asp=1)
vario=vario.calc(life)
plot(vario)
plot(vario,npairdw=TRUE)
#plot(vario,npairdw=TRUE,npairpt=TRUE)
#v_cloud=cloud.calc(life)
#plot(v_cloud)
model=model.auto(vario)
melem.name()
melem.name(c(1,2,3))
model.auto(vario,struct=melem.name(c(1,2,3)))
model.auto(vario,struct=melem.name(c(1,3,2)))
model.auto(vario,struct=melem.name(c(1,3,2)),maxiter=0)
model.auto(vario,struct=melem.name(c(1,2,3)),maxiter=0)
model.auto(vario,struct=melem.name(c(1,2,3)),flag.noreduce=T)

